version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: actualbudget_web
      APP_PORT: 5006
    
  web:
    image: docker.io/actualbudget/actual-server:latest
    user: "1000:1000"
    init: true

  volumes:
    - ${APP_DATA_DIR}/data:/data